[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
entity = { path = "../entity" }

anyhow = { version = "1.0", features = ["backtrace"] }
sea-orm = { version = "0.11", features = [ "sqlx-postgres", "runtime-tokio-rustls", "macros", "with-uuid" ] }
