[package]
name = "app_contract"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0", features = [] }
async-trait = { version = "0.1" }
uuid = { version = "1.3", features = [] }
