[package]
name = "secrethitler-web-api"
version = "0.1.0"
edition = "2021"

[dependencies]
#actix = "0.13.0"
actix-web = "4.0.1"
futures = "0.3.21"
uuid = { version = "1.0.0", features = ["v4"] }
#actix-web-actors = "4.1.0"
#juniper_actix = { version = "0.4.0", features = ["subscriptions"] }
juniper_actix = { git = "https://github.com/graphql-rust/juniper", branch = "master", features = ["subscriptions"] }
juniper_graphql_ws = { git = "https://github.com/graphql-rust/juniper", branch = "master" }
juniper = { git = "https://github.com/graphql-rust/juniper", branch = "master" }
#juniper = "0.15.9"
serde = { version = "1.0.136", features = ["derive"] }
actix-cors = "0.6.1"
syn = "1.0.95"
async-stream = "0.3"
