name: Secret Hitler CI
on:
  pull_request:
    branches: [dev, release]
jobs:
  run_tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v2

    - name: Build the backend
      run: cargo build --release --manifest-path=web_api/Cargo.toml

    - name: Start the API server
      run: web_api/target/release/secrethitler-web-api&

    - name: Install test dependencies
      run: npm i --prefix web_api/tests web_api/tests

    - name: Run backend tests
      run: npm t --prefix web_api/tests web_api/tests

    - name: Stop the server
      run: killall secrethitler-web-api
