name: Secret Hitler CI
on:
  pull_request:
    branches: [dev, release]
jobs:
  run_tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v2

# Rust backend
    - name: Build the backend
      working-directory: web_api
      run: cargo build --release

    - name: Start the API server
      working-directory: web_api
      run: target/release/secrethitler-web-api&

    - name: Install test dependencies
      working-directory: web_api/tests
      run: npm i

    - name: Run backend tests
      working-directory: web_api/tests
      run: npm t

# Flutter frontend
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Prepare linux build
      working-directory: flutter_client
      run: |
        sudo apt-get update -y
        sudo apt-get install -y clang ninja-build libgtk-3-dev
        flutter config --no-analytics
        flutter doctor -v

    - name: Get flutter dependencies
      working-directory: flutter_client
      run: flutter pub get

    - name: Build and test the flutter frontend client
      working-directory: flutter_client
      run: flutter test -d linux integration_test

# Cleanup
    - name: Stop the server
      run: killall secrethitler-web-api
