name: Secret Hitler CI
on:
  push:
    branches: [dev, release]
  pull_request:
    branches: [dev, release]

jobs:
  build_backend:
    strategy:
      matrix:
        os: [ubuntu-latest]
        toolchain: [stable]
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{matrix.toolchain}}
        override: true
    - name: Build
      run: cargo build --release
    - name: Upload binary
      uses: actions/upload-artifact@v3
      with:
        name: backend_build_${{runner.os}}_${{hashFiles('Cargo.toml', 'Cargo.lock', 'web_api/Cargo.toml', 'web_api/src/**')}}
        path: target/release/secrethitler-web-api

  lint_backend:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        toolchain: [ stable ]
    runs-on: ${{matrix.os}}
    needs: build_backend
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{matrix.toolchain}}
          components: rustfmt, clippy
          override: true
      - name: rustfmt
        run: cargo fmt --all -- --check
      - name: clippy
        run: cargo clippy -- -D warnings

  ci_flutter:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    needs: build_backend
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - name: Prepare linux build
      working-directory: flutter_client
      run: |
        sudo apt-get update -y
        sudo apt-get install -y clang ninja-build libgtk-3-dev
        flutter config --no-analytics
        flutter config --enable-linux-desktop
        flutter doctor -v
    - name: Get flutter dependencies
      working-directory: flutter_client
      run: flutter pub get
    - uses: actions/download-artifact@v3
      with:
        name: backend_build_${{runner.os}}_${{hashFiles('Cargo.toml', 'Cargo.lock', 'web_api/Cargo.toml', 'web_api/src/**')}}
    - name: Start the API server
      run: |
        chmod 701 secrethitler-web-api
        ./secrethitler-web-api&
    - name: Build and test the flutter frontend client
      working-directory: flutter_client
      run: |
        export DISPLAY=:99
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
        flutter test -d linux integration_test
    - name: Stop the API server
      run: killall secrethitler-web-api
